// Code generated by hertz generator.

package world

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Hello .
// @router /hello [GET]
func Hello(ctx context.Context, c *app.RequestContext) {
	var err error
	var req string
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		fmt.Println("EWEEEE")
		return
	}

	resp := new(string)

	c.JSON(consts.StatusOK, resp)
}

// Hello2 .
// @router /hello2 [GET]
func Hello2(ctx context.Context, c *app.RequestContext) {
	var err error
	var req string
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(string)

	c.JSON(consts.StatusOK, resp)
}
