// idl/hdemo/hdemoapi.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.26.1
// source: hdemoapi.proto

package hdemoapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "hdemo/biz/model/api"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HDemoAPIReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty" query:"name"`
}

func (x *HDemoAPIReq) Reset() {
	*x = HDemoAPIReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdemoapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HDemoAPIReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HDemoAPIReq) ProtoMessage() {}

func (x *HDemoAPIReq) ProtoReflect() protoreflect.Message {
	mi := &file_hdemoapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HDemoAPIReq.ProtoReflect.Descriptor instead.
func (*HDemoAPIReq) Descriptor() ([]byte, []int) {
	return file_hdemoapi_proto_rawDescGZIP(), []int{0}
}

func (x *HDemoAPIReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HDemoAPIResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RespBody string `protobuf:"bytes,1,opt,name=RespBody,proto3" form:"RespBody" json:"RespBody,omitempty" query:"RespBody"`
}

func (x *HDemoAPIResp) Reset() {
	*x = HDemoAPIResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hdemoapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HDemoAPIResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HDemoAPIResp) ProtoMessage() {}

func (x *HDemoAPIResp) ProtoReflect() protoreflect.Message {
	mi := &file_hdemoapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HDemoAPIResp.ProtoReflect.Descriptor instead.
func (*HDemoAPIResp) Descriptor() ([]byte, []int) {
	return file_hdemoapi_proto_rawDescGZIP(), []int{1}
}

func (x *HDemoAPIResp) GetRespBody() string {
	if x != nil {
		return x.RespBody
	}
	return ""
}

var File_hdemoapi_proto protoreflect.FileDescriptor

var file_hdemoapi_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x68, 0x64, 0x65, 0x6d, 0x6f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x68, 0x64, 0x65, 0x6d, 0x6f, 0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x0b, 0x48, 0x44, 0x65, 0x6d, 0x6f, 0x41, 0x50, 0x49, 0x52, 0x65,
	0x71, 0x12, 0x1c, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x08, 0xb2, 0xbb, 0x18, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x2a, 0x0a, 0x0c, 0x48, 0x44, 0x65, 0x6d, 0x6f, 0x41, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x42, 0x6f, 0x64, 0x79, 0x32, 0x92, 0x01, 0x0a, 0x0f,
	0x48, 0x44, 0x65, 0x6d, 0x6f, 0x41, 0x50, 0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3e, 0x0a, 0x07, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x31, 0x12, 0x12, 0x2e, 0x68, 0x64, 0x65,
	0x6d, 0x6f, 0x2e, 0x48, 0x44, 0x65, 0x6d, 0x6f, 0x41, 0x50, 0x49, 0x52, 0x65, 0x71, 0x1a, 0x13,
	0x2e, 0x68, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x48, 0x44, 0x65, 0x6d, 0x6f, 0x41, 0x50, 0x49, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x0a, 0xca, 0xc1, 0x18, 0x06, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12,
	0x3f, 0x0a, 0x07, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x33, 0x12, 0x12, 0x2e, 0x68, 0x64, 0x65,
	0x6d, 0x6f, 0x2e, 0x48, 0x44, 0x65, 0x6d, 0x6f, 0x41, 0x50, 0x49, 0x52, 0x65, 0x71, 0x1a, 0x13,
	0x2e, 0x68, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x48, 0x44, 0x65, 0x6d, 0x6f, 0x41, 0x50, 0x49, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x0b, 0xca, 0xc1, 0x18, 0x07, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x33,
	0x42, 0x1a, 0x5a, 0x18, 0x68, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2f, 0x68, 0x64, 0x65, 0x6d, 0x6f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hdemoapi_proto_rawDescOnce sync.Once
	file_hdemoapi_proto_rawDescData = file_hdemoapi_proto_rawDesc
)

func file_hdemoapi_proto_rawDescGZIP() []byte {
	file_hdemoapi_proto_rawDescOnce.Do(func() {
		file_hdemoapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_hdemoapi_proto_rawDescData)
	})
	return file_hdemoapi_proto_rawDescData
}

var file_hdemoapi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hdemoapi_proto_goTypes = []interface{}{
	(*HDemoAPIReq)(nil),  // 0: hdemo.HDemoAPIReq
	(*HDemoAPIResp)(nil), // 1: hdemo.HDemoAPIResp
}
var file_hdemoapi_proto_depIdxs = []int32{
	0, // 0: hdemo.HDemoAPIService.Method1:input_type -> hdemo.HDemoAPIReq
	0, // 1: hdemo.HDemoAPIService.Method3:input_type -> hdemo.HDemoAPIReq
	1, // 2: hdemo.HDemoAPIService.Method1:output_type -> hdemo.HDemoAPIResp
	1, // 3: hdemo.HDemoAPIService.Method3:output_type -> hdemo.HDemoAPIResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hdemoapi_proto_init() }
func file_hdemoapi_proto_init() {
	if File_hdemoapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hdemoapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HDemoAPIReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hdemoapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HDemoAPIResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hdemoapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hdemoapi_proto_goTypes,
		DependencyIndexes: file_hdemoapi_proto_depIdxs,
		MessageInfos:      file_hdemoapi_proto_msgTypes,
	}.Build()
	File_hdemoapi_proto = out.File
	file_hdemoapi_proto_rawDesc = nil
	file_hdemoapi_proto_goTypes = nil
	file_hdemoapi_proto_depIdxs = nil
}
