// Code generated by hertz generator.

package hdemoapi

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _method1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _method2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _method3Mw() []app.HandlerFunc {
	// your code...
	return nil
}
