// Code generated by hertz generator.

package world

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _helloMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hello2Mw() []app.HandlerFunc {
	// your code...
	return nil
}
