// Code generated by Kitex v0.12.1. DO NOT EDIT.

package expertservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	expert "kdemo/kitex_gen/api/expert"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	QuestionSearch(ctx context.Context, Req *expert.QuestionSearchReqBody, callOptions ...callopt.Option) (r *expert.QuestionSearchRes, err error)
	Hello(ctx context.Context, Req *expert.HelloReqBody, callOptions ...callopt.Option) (r *expert.HelloRes, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kExpertServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kExpertServiceClient struct {
	*kClient
}

func (p *kExpertServiceClient) QuestionSearch(ctx context.Context, Req *expert.QuestionSearchReqBody, callOptions ...callopt.Option) (r *expert.QuestionSearchRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QuestionSearch(ctx, Req)
}

func (p *kExpertServiceClient) Hello(ctx context.Context, Req *expert.HelloReqBody, callOptions ...callopt.Option) (r *expert.HelloRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Hello(ctx, Req)
}
