// Code generated by Kitex v0.12.1. DO NOT EDIT.

package expertservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	expert "kdemo/kitex_gen/api/expert"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"QuestionSearch": kitex.NewMethodInfo(
		questionSearchHandler,
		newQuestionSearchArgs,
		newQuestionSearchResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Hello": kitex.NewMethodInfo(
		helloHandler,
		newHelloArgs,
		newHelloResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	expertServiceServiceInfo                = NewServiceInfo()
	expertServiceServiceInfoForClient       = NewServiceInfoForClient()
	expertServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return expertServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return expertServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return expertServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ExpertService"
	handlerType := (*expert.ExpertService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api.expert",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.12.1",
		Extra:           extra,
	}
	return svcInfo
}

func questionSearchHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(expert.QuestionSearchReqBody)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(expert.ExpertService).QuestionSearch(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *QuestionSearchArgs:
		success, err := handler.(expert.ExpertService).QuestionSearch(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*QuestionSearchResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newQuestionSearchArgs() interface{} {
	return &QuestionSearchArgs{}
}

func newQuestionSearchResult() interface{} {
	return &QuestionSearchResult{}
}

type QuestionSearchArgs struct {
	Req *expert.QuestionSearchReqBody
}

func (p *QuestionSearchArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(expert.QuestionSearchReqBody)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *QuestionSearchArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *QuestionSearchArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *QuestionSearchArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *QuestionSearchArgs) Unmarshal(in []byte) error {
	msg := new(expert.QuestionSearchReqBody)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var QuestionSearchArgs_Req_DEFAULT *expert.QuestionSearchReqBody

func (p *QuestionSearchArgs) GetReq() *expert.QuestionSearchReqBody {
	if !p.IsSetReq() {
		return QuestionSearchArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *QuestionSearchArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *QuestionSearchArgs) GetFirstArgument() interface{} {
	return p.Req
}

type QuestionSearchResult struct {
	Success *expert.QuestionSearchRes
}

var QuestionSearchResult_Success_DEFAULT *expert.QuestionSearchRes

func (p *QuestionSearchResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(expert.QuestionSearchRes)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *QuestionSearchResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *QuestionSearchResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *QuestionSearchResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *QuestionSearchResult) Unmarshal(in []byte) error {
	msg := new(expert.QuestionSearchRes)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *QuestionSearchResult) GetSuccess() *expert.QuestionSearchRes {
	if !p.IsSetSuccess() {
		return QuestionSearchResult_Success_DEFAULT
	}
	return p.Success
}

func (p *QuestionSearchResult) SetSuccess(x interface{}) {
	p.Success = x.(*expert.QuestionSearchRes)
}

func (p *QuestionSearchResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *QuestionSearchResult) GetResult() interface{} {
	return p.Success
}

func helloHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(expert.HelloReqBody)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(expert.ExpertService).Hello(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *HelloArgs:
		success, err := handler.(expert.ExpertService).Hello(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*HelloResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newHelloArgs() interface{} {
	return &HelloArgs{}
}

func newHelloResult() interface{} {
	return &HelloResult{}
}

type HelloArgs struct {
	Req *expert.HelloReqBody
}

func (p *HelloArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(expert.HelloReqBody)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *HelloArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *HelloArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *HelloArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *HelloArgs) Unmarshal(in []byte) error {
	msg := new(expert.HelloReqBody)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var HelloArgs_Req_DEFAULT *expert.HelloReqBody

func (p *HelloArgs) GetReq() *expert.HelloReqBody {
	if !p.IsSetReq() {
		return HelloArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *HelloArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *HelloArgs) GetFirstArgument() interface{} {
	return p.Req
}

type HelloResult struct {
	Success *expert.HelloRes
}

var HelloResult_Success_DEFAULT *expert.HelloRes

func (p *HelloResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(expert.HelloRes)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *HelloResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *HelloResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *HelloResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *HelloResult) Unmarshal(in []byte) error {
	msg := new(expert.HelloRes)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *HelloResult) GetSuccess() *expert.HelloRes {
	if !p.IsSetSuccess() {
		return HelloResult_Success_DEFAULT
	}
	return p.Success
}

func (p *HelloResult) SetSuccess(x interface{}) {
	p.Success = x.(*expert.HelloRes)
}

func (p *HelloResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *HelloResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) QuestionSearch(ctx context.Context, Req *expert.QuestionSearchReqBody) (r *expert.QuestionSearchRes, err error) {
	var _args QuestionSearchArgs
	_args.Req = Req
	var _result QuestionSearchResult
	if err = p.c.Call(ctx, "QuestionSearch", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Hello(ctx context.Context, Req *expert.HelloReqBody) (r *expert.HelloRes, err error) {
	var _args HelloArgs
	_args.Req = Req
	var _result HelloResult
	if err = p.c.Call(ctx, "Hello", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
