// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAsset = "Asset"

// Asset mapped from table <Asset>
type Asset struct {
	ID     string `gorm:"column:ID;primaryKey;comment:主键" json:"ID"`          // 主键
	Key    string `gorm:"column:key;not null;comment:资产的唯一标识key" json:"key"`  // 资产的唯一标识key
	Alias_ string `gorm:"column:alias;not null;comment:别名：中文名等" json:"alias"` // 别名：中文名等
	Desc   string `gorm:"column:desc;comment:对资源的描述" json:"desc"`             // 对资源的描述
	Type   int32  `gorm:"column:type;not null;comment:资源的类型" json:"type"`     // 资源的类型
}

// TableName Asset's table name
func (*Asset) TableName() string {
	return TableNameAsset
}
