// Code generated by hertz generator.

package hdemoapi

import (
	"context"

	hdemoapi "hdemo/biz/model/hdemoapi"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Method1 .
// @router /hello [GET]
func Method1(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hdemoapi.HDemoAPIReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(hdemoapi.HDemoAPIResp)

	c.JSON(consts.StatusOK, resp)
}

// Method2 .
// @router /hello2 [GET]
func Method2(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hdemoapi.HDemoAPIReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(hdemoapi.HDemoAPIResp)

	c.JSON(consts.StatusOK, resp)
}

// Method3 .
// @router /hello3 [GET]
func Method3(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hdemoapi.HDemoAPIReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(hdemoapi.HDemoAPIResp)

	c.JSON(consts.StatusOK, resp)
}
