// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/demo/demo.proto

package demo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SexType int32

const (
	SexType_Male   SexType = 0
	SexType_Female SexType = 1
)

// Enum value maps for SexType.
var (
	SexType_name = map[int32]string{
		0: "Male",
		1: "Female",
	}
	SexType_value = map[string]int32{
		"Male":   0,
		"Female": 1,
	}
)

func (x SexType) Enum() *SexType {
	p := new(SexType)
	*p = x
	return p
}

func (x SexType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SexType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_demo_demo_proto_enumTypes[0].Descriptor()
}

func (SexType) Type() protoreflect.EnumType {
	return &file_proto_demo_demo_proto_enumTypes[0]
}

func (x SexType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SexType.Descriptor instead.
func (SexType) EnumDescriptor() ([]byte, []int) {
	return file_proto_demo_demo_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                        // 姓名
	Age     uint32  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`                         // 年龄
	Sex     SexType `protobuf:"varint,3,opt,name=sex,proto3,enum=proto.demo.SexType" json:"sex,omitempty"` // 性别
	Balance int64   `protobuf:"zigzag64,4,opt,name=balance,proto3" json:"balance,omitempty"`               // 余额(sint64 表达负数是占用更小)
	//@inject_tag: json:"lesson_source_map"
	LessonSourceMap map[string]int64   `protobuf:"bytes,5,rep,name=lesson_source_map,json=lessonSourceMap,proto3" json:"lesson_source_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // 课程分数（具体的map）
	Friends         []*User_FriendInfo `protobuf:"bytes,6,rep,name=friends,proto3" json:"friends,omitempty"`                                                                                                                                   // 朋友列表
	Loc             *Location          `protobuf:"bytes,7,opt,name=loc,proto3" json:"loc,omitempty"`                                                                                                                                           // 地址
	Sign            []byte             `protobuf:"bytes,8,opt,name=Sign,proto3" json:"Sign,omitempty"`                                                                                                                                         // 座右铭
	// oneof类型可以同时包含多个类型的字段，但是同时只能有一个字段被设置。在我们有多选一的需求时，oneof字段可强化这个行为，同时也能有节约内存的效果。
	// oneof内的字段和上一层的字段属于同一级别，因此不能重名
	//oneof内的字段不能用 Repeated 修饰
	//oneof内同时只能有一个字段被设置。如果oneof字段被重复设置，则以最后设置的结果为准
	//
	// Types that are assignable to OtherContact:
	//	*User_Qq
	//	*User_Wechat
	OtherContact isUser_OtherContact `protobuf_oneof:"other_contact"`
	Attrs        *structpb.Struct    `protobuf:"bytes,11,opt,name=attrs,proto3" json:"attrs,omitempty"` // 个人属性（单层结构体）
	Extra        *anypb.Any          `protobuf:"bytes,12,opt,name=extra,proto3" json:"extra,omitempty"` // 额外信息（不固定的内容）
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_demo_demo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_demo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_demo_demo_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User) GetSex() SexType {
	if x != nil {
		return x.Sex
	}
	return SexType_Male
}

func (x *User) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *User) GetLessonSourceMap() map[string]int64 {
	if x != nil {
		return x.LessonSourceMap
	}
	return nil
}

func (x *User) GetFriends() []*User_FriendInfo {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *User) GetLoc() *Location {
	if x != nil {
		return x.Loc
	}
	return nil
}

func (x *User) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

func (m *User) GetOtherContact() isUser_OtherContact {
	if m != nil {
		return m.OtherContact
	}
	return nil
}

func (x *User) GetQq() string {
	if x, ok := x.GetOtherContact().(*User_Qq); ok {
		return x.Qq
	}
	return ""
}

func (x *User) GetWechat() string {
	if x, ok := x.GetOtherContact().(*User_Wechat); ok {
		return x.Wechat
	}
	return ""
}

func (x *User) GetAttrs() *structpb.Struct {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *User) GetExtra() *anypb.Any {
	if x != nil {
		return x.Extra
	}
	return nil
}

type isUser_OtherContact interface {
	isUser_OtherContact()
}

type User_Qq struct {
	Qq string `protobuf:"bytes,9,opt,name=qq,proto3,oneof"`
}

type User_Wechat struct {
	Wechat string `protobuf:"bytes,10,opt,name=wechat,proto3,oneof"`
}

func (*User_Qq) isUser_OtherContact() {}

func (*User_Wechat) isUser_OtherContact() {}

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country string `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"` // 国家
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_demo_demo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_demo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_demo_demo_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type User_FriendInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 朋友姓名
}

func (x *User_FriendInfo) Reset() {
	*x = User_FriendInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_demo_demo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User_FriendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_FriendInfo) ProtoMessage() {}

func (x *User_FriendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_demo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_FriendInfo.ProtoReflect.Descriptor instead.
func (*User_FriendInfo) Descriptor() ([]byte, []int) {
	return file_proto_demo_demo_proto_rawDescGZIP(), []int{0, 1}
}

func (x *User_FriendInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_demo_demo_proto protoreflect.FileDescriptor

var file_proto_demo_demo_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x64, 0x65, 0x6d,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64,
	0x65, 0x6d, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb1, 0x04, 0x0a,
	0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x03, 0x73,
	0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x53, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03, 0x73,
	0x65, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x12, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x11,
	0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x61,
	0x70, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0f,
	0x6c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x70, 0x12,
	0x35, 0x0a, 0x07, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x12, 0x26, 0x0a, 0x03, 0x6c, 0x6f, 0x63, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x65, 0x6d, 0x6f,
	0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x6c, 0x6f, 0x63, 0x12, 0x12,
	0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x69,
	0x67, 0x6e, 0x12, 0x10, 0x0a, 0x02, 0x71, 0x71, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x02, 0x71, 0x71, 0x12, 0x18, 0x0a, 0x06, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x12, 0x2d,
	0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x12, 0x2a, 0x0a,
	0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x1a, 0x42, 0x0a, 0x14, 0x4c, 0x65, 0x73,
	0x73, 0x6f, 0x6e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x20, 0x0a,
	0x0a, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42,
	0x0f, 0x0a, 0x0d, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x22, 0x24, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x2a, 0x1f, 0x0a, 0x07, 0x53, 0x65, 0x78, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x61, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46,
	0x65, 0x6d, 0x61, 0x6c, 0x65, 0x10, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x64, 0x65, 0x6d,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_demo_demo_proto_rawDescOnce sync.Once
	file_proto_demo_demo_proto_rawDescData = file_proto_demo_demo_proto_rawDesc
)

func file_proto_demo_demo_proto_rawDescGZIP() []byte {
	file_proto_demo_demo_proto_rawDescOnce.Do(func() {
		file_proto_demo_demo_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_demo_demo_proto_rawDescData)
	})
	return file_proto_demo_demo_proto_rawDescData
}

var file_proto_demo_demo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_demo_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_demo_demo_proto_goTypes = []interface{}{
	(SexType)(0),            // 0: proto.demo.SexType
	(*User)(nil),            // 1: proto.demo.User
	(*Location)(nil),        // 2: proto.demo.Location
	nil,                     // 3: proto.demo.User.LessonSourceMapEntry
	(*User_FriendInfo)(nil), // 4: proto.demo.User.FriendInfo
	(*structpb.Struct)(nil), // 5: google.protobuf.Struct
	(*anypb.Any)(nil),       // 6: google.protobuf.Any
}
var file_proto_demo_demo_proto_depIdxs = []int32{
	0, // 0: proto.demo.User.sex:type_name -> proto.demo.SexType
	3, // 1: proto.demo.User.lesson_source_map:type_name -> proto.demo.User.LessonSourceMapEntry
	4, // 2: proto.demo.User.friends:type_name -> proto.demo.User.FriendInfo
	2, // 3: proto.demo.User.loc:type_name -> proto.demo.Location
	5, // 4: proto.demo.User.attrs:type_name -> google.protobuf.Struct
	6, // 5: proto.demo.User.extra:type_name -> google.protobuf.Any
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_demo_demo_proto_init() }
func file_proto_demo_demo_proto_init() {
	if File_proto_demo_demo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_demo_demo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_demo_demo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_demo_demo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User_FriendInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_demo_demo_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*User_Qq)(nil),
		(*User_Wechat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_demo_demo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_demo_demo_proto_goTypes,
		DependencyIndexes: file_proto_demo_demo_proto_depIdxs,
		EnumInfos:         file_proto_demo_demo_proto_enumTypes,
		MessageInfos:      file_proto_demo_demo_proto_msgTypes,
	}.Build()
	File_proto_demo_demo_proto = out.File
	file_proto_demo_demo_proto_rawDesc = nil
	file_proto_demo_demo_proto_goTypes = nil
	file_proto_demo_demo_proto_depIdxs = nil
}
